services:
  app:
    build:
      context: .
    container_name: docker-app-21
    environment:
      - SPRING_PROFILES_ACTIVE=h2
    ports:
      - "8080:8080"
  app-mysql:
    build:
      context: .
    container_name: docker-app-21-mysql
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.30
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: billing_engine
      MYSQL_USER: app
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: root
